name: Bug Foo
description: Something broke? Fix it now!
title: "[Bug]: "
labels: ["bug"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is this bug about?
      placeholder: What happened?
    validations:
      required: true
  - type: textarea
    id: definition-done
    attributes:
      label: Definition of Done
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: dropdown
    id: documentation-required
    attributes:
      label: Does this require documentation?
      multiple: false
      options:
        - No
        - All
        - Admin Guide
        - API Guide
        - User Guide
  - type: checkboxes
    id: terms
    attributes:
      label: Non-QC Task
      description: Is this a QC-related task?
      options:
        - label: This is a QC-related task
          required: false
