name: Bug Foo

description: Something broke? Fix it now!

title: "[Bug]: "

labels: ["bug"]

projects: ["octo-org/1", "octo-org/44"]

assignees:
  - octocat

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is this bug about?
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: definition-done
    attributes:
      label: Definition of Done
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Select the priority level
      multiple: false
      options:
        - Low
        - Medium
        - High

  - type: checkboxes
    id: fasb
    attributes:
      label: FASB
      description: Is this a FASB task?
      options:
        - label: FASB?
          required: false

  - type: dropdown
    id: billing-type
    attributes:
      label: Billing Type
      description: Is this a billable or non-billable task?
      multiple: false
      options:
        - Non-billable
        - Billable

  - type: input
    id: ui-change-page
    attributes:
      label: UI Change Page/Screen
      description: Specify the affected UI page or screen
      placeholder: e.g., Dashboard, Settings Page

  - type: input
    id: security-review-by
    attributes:
      label: Security Review By
      description: Who will conduct the security review?
      placeholder: Enter name or team

  - type: input
    id: estimated-work-hours
    attributes:
      label: Estimated work hours
      description: How long will it take to fix this bug?
      placeholder: 8 hours
    validations:
      required: true

  - type: dropdown
    id: security-significant
    attributes:
      label: Security Significance
      description: How significant is this issue for security?
      multiple: false
      options:
        - "Yes"
        - Potential
        - TBD

  - type: dropdown
    id: documentation-required
    attributes:
      label: Does this require documentation?
      multiple: false
      options:
        - All
        - Admin Guide
        - API Guide
        - User Guide

  - type: checkboxes
    id: terms
    attributes:
      label: Non-QC Task
      description: Is this a QC-related task?
      options:
        - label: This not a QC-related task
          required: false
